#!/usr/bin/env bash
# Displays information about subdomains.

domain_func () {
    Aip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4, $5}' | tail -1)
    echo "$2 $Aip" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_func "$1" "www"
  domain_func "$1" "lb-01"
  domain_func "$1" "web-01"
  domain_func "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_func "$1" "$2"
fi
