#!/usr/bin/env bash
# Installs nginx web server

sudo apt update
sudo apt install -y nginx
sudo service nginx start
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location / {
    	try_files $uri $uri/ =404;
	}
    
}" > /etc/nginx/sites-available/default

# To redirect 
NEW_LINE="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/3NPZ-VKoa9Q?si=ewsZuSenvTqyJs3P;\n\t}\n"

# replace a line with NEW_LINE
sudo sed -i "20i $NEW_LINE" /etc/nginx/sites-available/default

sudo service nginx restart
