#!/usr/bin/env bash
# Installs nginx web server

sudo apt update
sudo apt install -y nginx
sudo service nginx start
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location / {
    	try_files $uri $uri/ =404;
	}
    location /redirect_me {
        return 301 https://google.com;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
