#!/usr/bin/env bash
# Installs and configures nginx web server with a custom 404 page

# Update package list and install nginx
sudo apt-get update
sudo apt-get install nginx -y

# starting the nginx
sudo service nginx start

# setup to listen on port 80
sudo ufw allow 'Nginx HTTP'

# giving ownership and mode
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html/*

#create an index page
echo "Hello World!" | sudo tee var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx to use the custom 404 page
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://google.com;
    }

    # Custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
    	internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
