#!/usr/bin/env bash
# Installs and configures nginx web server with a custom 404 page

# Update package list and install nginx
apt-get update
apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx to use the custom 404 page
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://google.com;
    }

    # Custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default
